### ISSUE TITLE
Use standardjs for consistent linting

### ISSUE THREAD

**Issue by marcinczenko** [philips-software/react-cross-client-router#3]

**Comment by stam** [comment]
Is this necessary? This uses prettier w/ the airbnb standards which are a lot more popular than standardjs.

**Comment by marcinczenko** [comment]
Not strictly necessary, but what is better:

1. `.prettierrc`
2. `.eslintrc`
3. and the following packages as devDeps in `package.json`:
    
    ```json
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-react": "^7.10.0",
    ```

Or only this in `package.json`:

```json
"devDependencies":
  "babel-eslint": "^10.0.1",
  "standard": "^12.0.1"
}

"standard": {
    "parser": "babel-eslint",
    "ignore": [
      "**/node_modules/**"
    ]
  }
```

Uniformity within Philips Software is another thing worth underlying in this specific case.

**Comment by marcinczenko** [comment]
And, BTW, are the poor guys advocating using double quotes and semicolons at the end of the files? That's not what `standardjs` does so maybe something is not good with the setup.

**Comment by stam** [comment]
Yes semicolons are awesome: https://github.com/airbnb/javascript#semicolons

**Comment by marcinczenko** [comment]
No, there are not - google further and you will find out why. Airbnb is not ultimate reference for everything just because they are popular. I do not have time for such discussions. Philips Software uses standardjs and semicolons are not there. Please continue with @JeroenKnoops on it...
